"use strict";

var _require = require("./../endpoints_helpers.js"),
    authorizationHeaders = _require.authorizationHeaders;

/**
 * @typedef {{
 *   fees: string[],
 *   flexPasses: string[],
 *   parcels: string[],
 *   redeemableItems: string[],
 *   soldItems: string[],
 *   tickets: string[],
 *   giftCertificates: string[],
 *   insurances: string[],
 *   trxId: string,
 *   penalty?: {
 *      amount: number,
 *      reason: string
 *   }
 * }} CancelSetData
*/

function cancellationEndpointsFactory(_ref) {
  var client = _ref.client,
      internalAuthTokenProvider = _ref.internalAuthTokenProvider;

  /**
   * Creates a set of refundable items and payments to be refunded
   * @param {Object} params
   * @param {string} params.token Public key
   * @param {string} params.jwtToken Auth token
   * @param {CancelSetData} params.cancelData List of item ids grouped by family
   * @param {Object} params.headers HTTP Headers
   * @returns {Promise} A cancel set object
   */
  function createCancelSet(_ref2) {
    var token = _ref2.token,
        jwtToken = _ref2.jwtToken,
        cancelData = _ref2.cancelData,
        headers = _ref2.headers;

    return client({
      url: "/cancellations",
      method: "POST",
      data: {
        cancellation: cancelData
      },
      headers: authorizationHeaders({ token: token, jwtToken: jwtToken, internalAuthTokenProvider: internalAuthTokenProvider, headers: headers })
    });
  }

  /**
   * Creates and runs payment refunds
   * @param {Object} params
   * @param {string} params.token Public key
   * @param {string} params.jwtToken Auth token
   * @param {Object} params.cancelSet An unmodified cancel set object generated by the cancellations endpoint
   * @param {Object} params.headers HTTP Headers
   * @returns {Promise} Refund result
   */
  function createRefund(_ref3) {
    var token = _ref3.token,
        jwtToken = _ref3.jwtToken,
        cancelSet = _ref3.cancelSet,
        headers = _ref3.headers;

    return client({
      url: "/cancellations",
      method: "PUT",
      data: cancelSet,
      headers: authorizationHeaders({ token: token, jwtToken: jwtToken, internalAuthTokenProvider: internalAuthTokenProvider, headers: headers })
    });
  }

  return {
    sets: {
      create: createCancelSet
    },
    refunds: {
      create: createRefund
    }
  };
}

module.exports = cancellationEndpointsFactory;